### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by JasonasIgn** [Purii/react-use-scrollspy#167]
If I install the package on a typescript project, I get a warning:
Could not find a declaration file for module 'react-use-scrollspy'.

A declaration file should be added for typescript users

**Comment by Purii** [comment]
Hi @JasonasIgn!
It's on my list to migrate this component to ts soon. Fixes that issue without additional declaration file

**Comment by Purii** [comment]
Hi @JasonasIgn 
I just migrated the component to TS. So your issue should be fixed with [`v3.0.0`](https://github.com/Purii/react-use-scrollspy/blob/master/CHANGELOG.md#300-2021-01-23).

Feel free to me know if encounter further issues with the component in your TS project 👍
