### ISSUE TITLE
Get activeSection by ID instead of number

### ISSUE THREAD

**Issue by angelinekwan** [Purii/react-use-scrollspy#342]
Could you kindly advice on how to get the `activeSection` by sectionRefs id? Currently it is returning the index of the sectionRefs - 0, 1, 2 . I would need to return by `sectionRefs.getAttribute(id)` because the order of the section might differ than the navigation.

import React, { useRef } from 'react';
import useScrollSpy from 'react-use-scrollspy';

const App = () => {

  const sectionRefs = [
    useRef(null),
    useRef(null),
    useRef(null),
  ];

  const activeSection = useScrollSpy({
    sectionElementRefs: sectionRefs,
    offsetPx: -80,
  });

`console.log(activeSection); ----> currently getting the index of the sectionRefs - 0, 1, 2 . Option to return by sectionRefs.getAttribute(id) because the order of the section might differ than the navigation.`

  return (
    <nav className="App-navigation">
      <span className={activeSection === "section-1" ? "active" : ""}>Section 1</span>
      <span className={activeSection === "section-2" ? "active" : ""}>Section 2</span>
      <span className={activeSection === "section-3"? "active" : ""}>Section 3</span>
    </nav>

    <section id="section-1" ref={sectionRefs[0]}>
      <h1>Section 1</h1>
    </section>
    <section id="section-2" ref={sectionRefs[1]}>
      <h1>Section 2</h1>
    </section>
    <section id="section-3" ref={sectionRefs[2]}>
      <h1>Section 3</h1>
    </section>
  )

**Comment by Purii** [comment]
Hi @angelinekwan !

So you want to get the actual active element, right?

```js
const currentlyActiveElement = sectionRefs[activeSection]?.current?.getAttribute('id');

console.log(currentlyActiveElement);
```

**Comment by angelinekwan** [comment]
Thanks @Purii. My brain was stuck and thanks for unlocking this. Keep up the great work!
