### ISSUE TITLE
 ERROR in ./node_modules/react-use-scrollspy/lib/module/index.js 23:44     Module parse failed: Unexpected token (23:44)     You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file

### ISSUE THREAD

**Issue by nirmalantony** [Purii/react-use-scrollspy#438]

**Comment by Purii** [comment]
Which node version are you using @nirmalantony ?

The library is transpiled with target "ESNext" (see [`tsconfig.json`](https://github.com/Purii/react-use-scrollspy/blob/main/tsconfig.json)). That means you should consider transpiling your node_modules to exactly the target that you require. Is that an option?

**Comment by nirmalantony** [comment]
@Purii 
If we update the code   `const scrollable = scrollingElement?.current ?? window ` to
`const scrollable = scrollingElement? scrollingElement.current : window `
this will work

**Comment by Purii** [comment]
The nullish coalescing operator is nothing completely new and should work starting from [node@14](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing#browser_compatibility) and more than 90% of the used browser versions as stated by [caniuse](https://caniuse.com/?search=Nullish%20coalescing%20operator). So is the [optional chaining operator](https://caniuse.com/?search=optional%20chaining).
That's exactly the fact I pointed out. I guess that most people have recent versions of node installed and serve recent browsers. Everyone has different ranges of browsers and node versions to support, so the bundle should be transpiled based on the requirements of each individual project.

You're totally right, it's just a small change. But that already violate the above mentioned principle.
